# Generated by Django 5.1.7 on 2025-04-01 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('trip_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress')], default='in-progress', max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='auth_app.trip')),
            ],
        ),
    ]
