# Generated by Django 5.1.7 on 2025-04-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='address',
        ),
    ]
