# Generated by Django 5.1.7 on 2025-04-01 22:11

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_trip_id_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE auth_app_trip CHANGE COLUMN trip_id trip_id BIGINT;",
            reverse_sql="ALTER TABLE auth_app_trip CHANGE COLUMN trip_id trip_id BIGINT;"
        ),
    ]
