# Generated by Django 5.1.7 on 2025-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_car_license_plate'),
    ]

    operations = [
        # Prevent dropping the 'id' field until all references are updated
        # migrations.RemoveField(
        #     model_name='trip',
        #     name='id',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(default='TEMP12345', max_length=12, primary_key=True, serialize=False),
        ),
    ]
