# Generated by Django 5.1.7 on 2025-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_car_license_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='id',
        ),
    ]
