# Generated by Django 5.1.7 on 2025-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_trip_id_trip_trip_id'),
    ]

    operations = [
        # Keeping the id field as it is essential for the Trip model
    ]
