# Generated by Django 5.1.7 on 2025-04-02 02:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.BigIntegerField(primary_key=True),  # Set as primary key without auto-increment
        ),
    ]
