# Generated by Django 5.1.7 on 2025-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_update_trip_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
