# Generated by Django 5.1.7 on 2025-04-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('auth_app', '0007_revert_trip_id_migration'),
    ('auth_app', '0008_remove_trip_id_migration'),
]
 

    operations = []
