# Generated by Django 5.1.7 on 2025-04-02 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('trip_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress')], default='in-progress', max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings_tracking', to='auth_app.trip')),
            ],
        ),
    ]
