# Generated by Django 5.1.7 on 2025-04-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='trip',
            field=models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, to='auth_app.trip'),
        ),
    ]
